setblock ~1 ~ ~1 redstone_lamp 0 replace
setblock ~1 ~ ~2 redstone_block 0 replace
setblock ~1 ~ ~3 redstone_lamp 0 replace
setblock ~1 ~ ~4 redstone_block 0 replace
setblock ~1 ~ ~5 redstone_lamp 0 replace
setblock ~1 ~ ~6 redstone_block 0 replace
setblock ~1 ~ ~7 redstone_lamp 0 replace
setblock ~1 ~ ~8 redstone_block 0 replace
setblock ~1 ~ ~9 redstone_lamp 0 replace
setblock ~1 ~ ~10 redstone_block 0 replace
setblock ~1 ~ ~11 redstone_lamp 0 replace
setblock ~1 ~ ~12 redstone_block 0 replace
setblock ~1 ~ ~13 redstone_lamp 0 replace
setblock ~1 ~ ~14 redstone_block 0 replace
setblock ~1 ~ ~15 redstone_lamp 0 replace
setblock ~1 ~ ~16 redstone_block 0 replace
setblock ~2 ~ ~1 redstone_block 0 replace
setblock ~2 ~ ~2 redstone_lamp 0 replace
setblock ~2 ~ ~3 redstone_block 0 replace
setblock ~2 ~ ~4 redstone_lamp 0 replace
setblock ~2 ~ ~5 redstone_block 0 replace
setblock ~2 ~ ~6 redstone_lamp 0 replace
setblock ~2 ~ ~7 redstone_block 0 replace
setblock ~2 ~ ~8 redstone_lamp 0 replace
setblock ~2 ~ ~9 redstone_block 0 replace
setblock ~2 ~ ~10 redstone_lamp 0 replace
setblock ~2 ~ ~11 redstone_block 0 replace
setblock ~2 ~ ~12 redstone_lamp 0 replace
setblock ~2 ~ ~13 redstone_block 0 replace
setblock ~2 ~ ~14 redstone_lamp 0 replace
setblock ~2 ~ ~15 redstone_block 0 replace
setblock ~2 ~ ~16 redstone_lamp 0 replace
setblock ~3 ~ ~1 redstone_lamp 0 replace
setblock ~3 ~ ~2 redstone_block 0 replace
setblock ~3 ~ ~3 redstone_lamp 0 replace
setblock ~3 ~ ~4 redstone_block 0 replace
setblock ~3 ~ ~5 redstone_lamp 0 replace
setblock ~3 ~ ~6 redstone_block 0 replace
setblock ~3 ~ ~7 redstone_lamp 0 replace
setblock ~3 ~ ~8 redstone_block 0 replace
setblock ~3 ~ ~9 redstone_lamp 0 replace
setblock ~3 ~ ~10 redstone_block 0 replace
setblock ~3 ~ ~11 redstone_lamp 0 replace
setblock ~3 ~ ~12 redstone_block 0 replace
setblock ~3 ~ ~13 redstone_lamp 0 replace
setblock ~3 ~ ~14 redstone_block 0 replace
setblock ~3 ~ ~15 redstone_lamp 0 replace
setblock ~3 ~ ~16 redstone_block 0 replace
setblock ~4 ~ ~1 redstone_block 0 replace
setblock ~4 ~ ~2 redstone_lamp 0 replace
setblock ~4 ~ ~3 redstone_block 0 replace
setblock ~4 ~ ~4 redstone_lamp 0 replace
setblock ~4 ~ ~5 redstone_block 0 replace
setblock ~4 ~ ~6 redstone_lamp 0 replace
setblock ~4 ~ ~7 redstone_block 0 replace
setblock ~4 ~ ~8 redstone_lamp 0 replace
setblock ~4 ~ ~9 redstone_block 0 replace
setblock ~4 ~ ~10 redstone_lamp 0 replace
setblock ~4 ~ ~11 redstone_block 0 replace
setblock ~4 ~ ~12 redstone_lamp 0 replace
setblock ~4 ~ ~13 redstone_block 0 replace
setblock ~4 ~ ~14 redstone_lamp 0 replace
setblock ~4 ~ ~15 redstone_block 0 replace
setblock ~4 ~ ~16 redstone_lamp 0 replace
setblock ~5 ~ ~1 redstone_lamp 0 replace
setblock ~5 ~ ~2 redstone_block 0 replace
setblock ~5 ~ ~3 redstone_lamp 0 replace
setblock ~5 ~ ~4 redstone_block 0 replace
setblock ~5 ~ ~5 redstone_lamp 0 replace
setblock ~5 ~ ~6 redstone_block 0 replace
setblock ~5 ~ ~7 redstone_lamp 0 replace
setblock ~5 ~ ~8 redstone_block 0 replace
setblock ~5 ~ ~9 redstone_lamp 0 replace
setblock ~5 ~ ~10 redstone_block 0 replace
setblock ~5 ~ ~11 redstone_lamp 0 replace
setblock ~5 ~ ~12 redstone_block 0 replace
setblock ~5 ~ ~13 redstone_lamp 0 replace
setblock ~5 ~ ~14 redstone_block 0 replace
setblock ~5 ~ ~15 redstone_lamp 0 replace
setblock ~5 ~ ~16 redstone_block 0 replace
setblock ~6 ~ ~1 redstone_block 0 replace
setblock ~6 ~ ~2 redstone_lamp 0 replace
setblock ~6 ~ ~3 redstone_block 0 replace
setblock ~6 ~ ~4 redstone_lamp 0 replace
setblock ~6 ~ ~5 redstone_block 0 replace
setblock ~6 ~ ~6 redstone_lamp 0 replace
setblock ~6 ~ ~7 redstone_block 0 replace
setblock ~6 ~ ~8 redstone_lamp 0 replace
setblock ~6 ~ ~9 redstone_block 0 replace
setblock ~6 ~ ~10 redstone_lamp 0 replace
setblock ~6 ~ ~11 redstone_block 0 replace
setblock ~6 ~ ~12 redstone_lamp 0 replace
setblock ~6 ~ ~13 redstone_block 0 replace
setblock ~6 ~ ~14 redstone_lamp 0 replace
setblock ~6 ~ ~15 redstone_block 0 replace
setblock ~6 ~ ~16 redstone_lamp 0 replace
setblock ~7 ~ ~1 redstone_lamp 0 replace
setblock ~7 ~ ~2 redstone_block 0 replace
setblock ~7 ~ ~3 redstone_lamp 0 replace
setblock ~7 ~ ~4 redstone_block 0 replace
setblock ~7 ~ ~5 redstone_lamp 0 replace
setblock ~7 ~ ~6 redstone_block 0 replace
setblock ~7 ~ ~7 redstone_lamp 0 replace
setblock ~7 ~ ~8 redstone_block 0 replace
setblock ~7 ~ ~9 redstone_lamp 0 replace
setblock ~7 ~ ~10 redstone_block 0 replace
setblock ~7 ~ ~11 redstone_lamp 0 replace
setblock ~7 ~ ~12 redstone_block 0 replace
setblock ~7 ~ ~13 redstone_lamp 0 replace
setblock ~7 ~ ~14 redstone_block 0 replace
setblock ~7 ~ ~15 redstone_lamp 0 replace
setblock ~7 ~ ~16 redstone_block 0 replace
setblock ~8 ~ ~1 redstone_block 0 replace
setblock ~8 ~ ~2 redstone_lamp 0 replace
setblock ~8 ~ ~3 redstone_block 0 replace
setblock ~8 ~ ~4 redstone_lamp 0 replace
setblock ~8 ~ ~5 redstone_block 0 replace
setblock ~8 ~ ~6 redstone_lamp 0 replace
setblock ~8 ~ ~7 redstone_block 0 replace
setblock ~8 ~ ~8 redstone_lamp 0 replace
setblock ~8 ~ ~9 redstone_block 0 replace
setblock ~8 ~ ~10 redstone_lamp 0 replace
setblock ~8 ~ ~11 redstone_block 0 replace
setblock ~8 ~ ~12 redstone_lamp 0 replace
setblock ~8 ~ ~13 redstone_block 0 replace
setblock ~8 ~ ~14 redstone_lamp 0 replace
setblock ~8 ~ ~15 redstone_block 0 replace
setblock ~8 ~ ~16 redstone_lamp 0 replace
setblock ~9 ~ ~1 redstone_lamp 0 replace
setblock ~9 ~ ~2 redstone_block 0 replace
setblock ~9 ~ ~3 redstone_lamp 0 replace
setblock ~9 ~ ~4 redstone_block 0 replace
setblock ~9 ~ ~5 redstone_lamp 0 replace
setblock ~9 ~ ~6 redstone_block 0 replace
setblock ~9 ~ ~7 redstone_lamp 0 replace
setblock ~9 ~ ~8 redstone_block 0 replace
setblock ~9 ~ ~9 redstone_lamp 0 replace
setblock ~9 ~ ~10 redstone_block 0 replace
setblock ~9 ~ ~11 redstone_lamp 0 replace
setblock ~9 ~ ~12 redstone_block 0 replace
setblock ~9 ~ ~13 redstone_lamp 0 replace
setblock ~9 ~ ~14 redstone_block 0 replace
setblock ~9 ~ ~15 redstone_lamp 0 replace
setblock ~9 ~ ~16 redstone_block 0 replace
setblock ~10 ~ ~1 redstone_block 0 replace
setblock ~10 ~ ~2 redstone_lamp 0 replace
setblock ~10 ~ ~3 redstone_block 0 replace
setblock ~10 ~ ~4 redstone_lamp 0 replace
setblock ~10 ~ ~5 redstone_block 0 replace
setblock ~10 ~ ~6 redstone_lamp 0 replace
setblock ~10 ~ ~7 redstone_block 0 replace
setblock ~10 ~ ~8 redstone_lamp 0 replace
setblock ~10 ~ ~9 redstone_block 0 replace
setblock ~10 ~ ~10 redstone_lamp 0 replace
setblock ~10 ~ ~11 redstone_block 0 replace
setblock ~10 ~ ~12 redstone_lamp 0 replace
setblock ~10 ~ ~13 redstone_block 0 replace
setblock ~10 ~ ~14 redstone_lamp 0 replace
setblock ~10 ~ ~15 redstone_block 0 replace
setblock ~10 ~ ~16 redstone_lamp 0 replace
setblock ~11 ~ ~1 redstone_lamp 0 replace
setblock ~11 ~ ~2 redstone_block 0 replace
setblock ~11 ~ ~3 redstone_lamp 0 replace
setblock ~11 ~ ~4 redstone_block 0 replace
setblock ~11 ~ ~5 redstone_lamp 0 replace
setblock ~11 ~ ~6 redstone_block 0 replace
setblock ~11 ~ ~7 redstone_lamp 0 replace
setblock ~11 ~ ~8 redstone_block 0 replace
setblock ~11 ~ ~9 redstone_lamp 0 replace
setblock ~11 ~ ~10 redstone_block 0 replace
setblock ~11 ~ ~11 redstone_lamp 0 replace
setblock ~11 ~ ~12 redstone_block 0 replace
setblock ~11 ~ ~13 redstone_lamp 0 replace
setblock ~11 ~ ~14 redstone_block 0 replace
setblock ~11 ~ ~15 redstone_lamp 0 replace
setblock ~11 ~ ~16 redstone_block 0 replace
setblock ~12 ~ ~1 redstone_block 0 replace
setblock ~12 ~ ~2 redstone_lamp 0 replace
setblock ~12 ~ ~3 redstone_block 0 replace
setblock ~12 ~ ~4 redstone_lamp 0 replace
setblock ~12 ~ ~5 redstone_block 0 replace
setblock ~12 ~ ~6 redstone_lamp 0 replace
setblock ~12 ~ ~7 redstone_block 0 replace
setblock ~12 ~ ~8 redstone_lamp 0 replace
setblock ~12 ~ ~9 redstone_block 0 replace
setblock ~12 ~ ~10 redstone_lamp 0 replace
setblock ~12 ~ ~11 redstone_block 0 replace
setblock ~12 ~ ~12 redstone_lamp 0 replace
setblock ~12 ~ ~13 redstone_block 0 replace
setblock ~12 ~ ~14 redstone_lamp 0 replace
setblock ~12 ~ ~15 redstone_block 0 replace
setblock ~12 ~ ~16 redstone_lamp 0 replace
setblock ~13 ~ ~1 redstone_lamp 0 replace
setblock ~13 ~ ~2 redstone_block 0 replace
setblock ~13 ~ ~3 redstone_lamp 0 replace
setblock ~13 ~ ~4 redstone_block 0 replace
setblock ~13 ~ ~5 redstone_lamp 0 replace
setblock ~13 ~ ~6 redstone_block 0 replace
setblock ~13 ~ ~7 redstone_lamp 0 replace
setblock ~13 ~ ~8 redstone_block 0 replace
setblock ~13 ~ ~9 redstone_lamp 0 replace
setblock ~13 ~ ~10 redstone_block 0 replace
setblock ~13 ~ ~11 redstone_lamp 0 replace
setblock ~13 ~ ~12 redstone_block 0 replace
setblock ~13 ~ ~13 redstone_lamp 0 replace
setblock ~13 ~ ~14 redstone_block 0 replace
setblock ~13 ~ ~15 redstone_lamp 0 replace
setblock ~13 ~ ~16 redstone_block 0 replace
setblock ~14 ~ ~1 redstone_block 0 replace
setblock ~14 ~ ~2 redstone_lamp 0 replace
setblock ~14 ~ ~3 redstone_block 0 replace
setblock ~14 ~ ~4 redstone_lamp 0 replace
setblock ~14 ~ ~5 redstone_block 0 replace
setblock ~14 ~ ~6 redstone_lamp 0 replace
setblock ~14 ~ ~7 redstone_block 0 replace
setblock ~14 ~ ~8 redstone_lamp 0 replace
setblock ~14 ~ ~9 redstone_block 0 replace
setblock ~14 ~ ~10 redstone_lamp 0 replace
setblock ~14 ~ ~11 redstone_block 0 replace
setblock ~14 ~ ~12 redstone_lamp 0 replace
setblock ~14 ~ ~13 redstone_block 0 replace
setblock ~14 ~ ~14 redstone_lamp 0 replace
setblock ~14 ~ ~15 redstone_block 0 replace
setblock ~14 ~ ~16 redstone_lamp 0 replace
setblock ~15 ~ ~1 redstone_lamp 0 replace
setblock ~15 ~ ~2 redstone_block 0 replace
setblock ~15 ~ ~3 redstone_lamp 0 replace
setblock ~15 ~ ~4 redstone_block 0 replace
setblock ~15 ~ ~5 redstone_lamp 0 replace
setblock ~15 ~ ~6 redstone_block 0 replace
setblock ~15 ~ ~7 redstone_lamp 0 replace
setblock ~15 ~ ~8 redstone_block 0 replace
setblock ~15 ~ ~9 redstone_lamp 0 replace
setblock ~15 ~ ~10 redstone_block 0 replace
setblock ~15 ~ ~11 redstone_lamp 0 replace
setblock ~15 ~ ~12 redstone_block 0 replace
setblock ~15 ~ ~13 redstone_lamp 0 replace
setblock ~15 ~ ~14 redstone_block 0 replace
setblock ~15 ~ ~15 redstone_lamp 0 replace
setblock ~15 ~ ~16 redstone_block 0 replace
setblock ~16 ~ ~1 redstone_block 0 replace
setblock ~16 ~ ~2 redstone_lamp 0 replace
setblock ~16 ~ ~3 redstone_block 0 replace
setblock ~16 ~ ~4 redstone_lamp 0 replace
setblock ~16 ~ ~5 redstone_block 0 replace
setblock ~16 ~ ~6 redstone_lamp 0 replace
setblock ~16 ~ ~7 redstone_block 0 replace
setblock ~16 ~ ~8 redstone_lamp 0 replace
setblock ~16 ~ ~9 redstone_block 0 replace
setblock ~16 ~ ~10 redstone_lamp 0 replace
setblock ~16 ~ ~11 redstone_block 0 replace
setblock ~16 ~ ~12 redstone_lamp 0 replace
setblock ~16 ~ ~13 redstone_block 0 replace
setblock ~16 ~ ~14 redstone_lamp 0 replace
setblock ~16 ~ ~15 redstone_block 0 replace
setblock ~16 ~ ~16 redstone_lamp 0 replace
