git mv -k java/assets/minecraft/textures/block/cobblestone_mossy_n.png java/assets/minecraft/textures/block/mossy_cobblestone_n.png
git mv -k java/assets/minecraft/textures/block/cobblestone_mossy_s.png java/assets/minecraft/textures/block/mossy_cobblestone_s.png
git mv -k java/assets/minecraft/textures/block/cobblestone_mossy.png java/assets/minecraft/textures/block/mossy_cobblestone.png
git mv -k java/assets/minecraft/textures/block/concrete_black_n.png java/assets/minecraft/textures/block/black_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_black_s.png java/assets/minecraft/textures/block/black_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_black.png java/assets/minecraft/textures/block/black_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_blue_n.png java/assets/minecraft/textures/block/blue_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_blue_s.png java/assets/minecraft/textures/block/blue_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_blue.png java/assets/minecraft/textures/block/blue_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_brown_n.png java/assets/minecraft/textures/block/brown_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_brown_s.png java/assets/minecraft/textures/block/brown_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_brown.png java/assets/minecraft/textures/block/brown_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_cyan_n.png java/assets/minecraft/textures/block/cyan_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_cyan_s.png java/assets/minecraft/textures/block/cyan_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_cyan.png java/assets/minecraft/textures/block/cyan_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_gray_n.png java/assets/minecraft/textures/block/gray_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_gray_s.png java/assets/minecraft/textures/block/gray_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_gray.png java/assets/minecraft/textures/block/gray_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_green_n.png java/assets/minecraft/textures/block/green_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_green_s.png java/assets/minecraft/textures/block/green_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_green.png java/assets/minecraft/textures/block/green_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_light_blue_n.png java/assets/minecraft/textures/block/light_blue_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_light_blue_s.png java/assets/minecraft/textures/block/light_blue_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_light_blue.png java/assets/minecraft/textures/block/light_blue_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_lime_n.png java/assets/minecraft/textures/block/lime_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_lime_s.png java/assets/minecraft/textures/block/lime_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_lime.png java/assets/minecraft/textures/block/lime_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_magenta_n.png java/assets/minecraft/textures/block/magenta_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_magenta.png java/assets/minecraft/textures/block/magenta_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_orange_s.png java/assets/minecraft/textures/block/orange_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_orange.png java/assets/minecraft/textures/block/orange_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_organge_n.png java/assets/minecraft/textures/block/organge_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_pink_n.png java/assets/minecraft/textures/block/pink_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_pink_s.png java/assets/minecraft/textures/block/pink_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_pink.png java/assets/minecraft/textures/block/pink_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_black_n.png java/assets/minecraft/textures/block/black_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_black_s.png java/assets/minecraft/textures/block/black_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_black.png java/assets/minecraft/textures/block/black_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_blue_n.png java/assets/minecraft/textures/block/blue_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_blue_s.png java/assets/minecraft/textures/block/blue_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_blue.png java/assets/minecraft/textures/block/blue_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_brown_n.png java/assets/minecraft/textures/block/brown_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_brown_s.png java/assets/minecraft/textures/block/brown_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_brown.png java/assets/minecraft/textures/block/brown_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_cyan_n.png java/assets/minecraft/textures/block/cyan_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_cyan_s.png java/assets/minecraft/textures/block/cyan_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_cyan.png java/assets/minecraft/textures/block/cyan_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_gray_n.png java/assets/minecraft/textures/block/gray_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_gray_s.png java/assets/minecraft/textures/block/gray_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_gray.png java/assets/minecraft/textures/block/gray_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_green_n.png java/assets/minecraft/textures/block/green_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_green_s.png java/assets/minecraft/textures/block/green_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_green.png java/assets/minecraft/textures/block/green_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_light_blue_n.png java/assets/minecraft/textures/block/light_blue_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_light_blue_s.png java/assets/minecraft/textures/block/light_blue_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_light_blue.png java/assets/minecraft/textures/block/light_blue_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_lime_n.png java/assets/minecraft/textures/block/lime_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_lime_s.png java/assets/minecraft/textures/block/lime_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_lime.png java/assets/minecraft/textures/block/lime_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_magenta_n.png java/assets/minecraft/textures/block/magenta_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_magenta.png java/assets/minecraft/textures/block/magenta_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_orange_s.png java/assets/minecraft/textures/block/orange_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_orange.png java/assets/minecraft/textures/block/orange_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_organge_n.png java/assets/minecraft/textures/block/organge_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_pink_n.png java/assets/minecraft/textures/block/pink_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_pink_s.png java/assets/minecraft/textures/block/pink_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_pink.png java/assets/minecraft/textures/block/pink_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_purple_n.png java/assets/minecraft/textures/block/purple_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_purple_s.png java/assets/minecraft/textures/block/purple_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_purple.png java/assets/minecraft/textures/block/purple_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_red_n.png java/assets/minecraft/textures/block/red_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_red_s.png java/assets/minecraft/textures/block/red_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_red.png java/assets/minecraft/textures/block/red_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_silver_n.png java/assets/minecraft/textures/block/light_gray_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_silver_s.png java/assets/minecraft/textures/block/light_gray_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_silver.png java/assets/minecraft/textures/block/light_gray_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_white_n.png java/assets/minecraft/textures/block/white_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_white_s.png java/assets/minecraft/textures/block/white_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_white.png java/assets/minecraft/textures/block/white_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_yellow_n.png java/assets/minecraft/textures/block/yellow_concrete_powder_n.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_yellow_s.png java/assets/minecraft/textures/block/yellow_concrete_powder_s.png
git mv -k java/assets/minecraft/textures/block/concrete_powder_yellow.png java/assets/minecraft/textures/block/yellow_concrete_powder.png
git mv -k java/assets/minecraft/textures/block/concrete_purple_n.png java/assets/minecraft/textures/block/purple_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_purple_s.png java/assets/minecraft/textures/block/purple_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_purple.png java/assets/minecraft/textures/block/purple_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_red_n.png java/assets/minecraft/textures/block/red_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_red_s.png java/assets/minecraft/textures/block/red_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_red.png java/assets/minecraft/textures/block/red_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_silver_n.png java/assets/minecraft/textures/block/light_gray_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_silver_s.png java/assets/minecraft/textures/block/light_gray_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_silver.png java/assets/minecraft/textures/block/light_gray_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_white_n.png java/assets/minecraft/textures/block/white_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_white_s.png java/assets/minecraft/textures/block/white_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_white.png java/assets/minecraft/textures/block/white_concrete.png
git mv -k java/assets/minecraft/textures/block/concrete_yellow_n.png java/assets/minecraft/textures/block/yellow_concrete_n.png
git mv -k java/assets/minecraft/textures/block/concrete_yellow_s.png java/assets/minecraft/textures/block/yellow_concrete_s.png
git mv -k java/assets/minecraft/textures/block/concrete_yellow.png java/assets/minecraft/textures/block/yellow_concrete.png
git mv -k java/assets/minecraft/textures/block/door_acacia_lower_n.png java/assets/minecraft/textures/block/acacia_door_bottom_n.png
git mv -k java/assets/minecraft/textures/block/door_acacia_lower_s.png java/assets/minecraft/textures/block/acacia_door_bottom_s.png
git mv -k java/assets/minecraft/textures/block/door_acacia_lower.png java/assets/minecraft/textures/block/acacia_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_acacia_upper_n.png java/assets/minecraft/textures/block/acacia_door_top_n.png
git mv -k java/assets/minecraft/textures/block/door_acacia_upper_s.png java/assets/minecraft/textures/block/acacia_door_top_s.png
git mv -k java/assets/minecraft/textures/block/door_acacia_upper.png java/assets/minecraft/textures/block/acacia_door_top.png
git mv -k java/assets/minecraft/textures/block/door_birch_lower_n.png java/assets/minecraft/textures/block/birch_door_bottom_n.png
git mv -k java/assets/minecraft/textures/block/door_birch_lower_s.png java/assets/minecraft/textures/block/birch_door_bottom_s.png
git mv -k java/assets/minecraft/textures/block/door_birch_lower.png java/assets/minecraft/textures/block/birch_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_birch_upper_n.png java/assets/minecraft/textures/block/birch_door_top_n.png
git mv -k java/assets/minecraft/textures/block/door_birch_upper_s.png java/assets/minecraft/textures/block/birch_door_top_s.png
git mv -k java/assets/minecraft/textures/block/door_birch_upper.png java/assets/minecraft/textures/block/birch_door_top.png
git mv -k java/assets/minecraft/textures/block/door_crimson_lower_n.png java/assets/minecraft/textures/block/crimson_door_bottom_n.png
git mv -k java/assets/minecraft/textures/block/door_crimson_lower_s.png java/assets/minecraft/textures/block/crimson_door_bottom_s.png
git mv -k java/assets/minecraft/textures/block/door_crimson_lower.png java/assets/minecraft/textures/block/crimson_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_crimson_upper_n.png java/assets/minecraft/textures/block/crimson_door_top_n.png
git mv -k java/assets/minecraft/textures/block/door_crimson_upper_s.png java/assets/minecraft/textures/block/crimson_door_top_s.png
git mv -k java/assets/minecraft/textures/block/door_crimson_upper.png java/assets/minecraft/textures/block/crimson_door_top.png
git mv -k java/assets/minecraft/textures/block/door_dark_oak_lower.png java/assets/minecraft/textures/block/dark_oak_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_dark_oak_upper.png java/assets/minecraft/textures/block/dark_oak_door_top.png
git mv -k java/assets/minecraft/textures/block/door_iron_lower.png java/assets/minecraft/textures/block/iron_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_iron_upper.png java/assets/minecraft/textures/block/iron_door_top.png
git mv -k java/assets/minecraft/textures/block/door_warped_lower_n.png java/assets/minecraft/textures/block/warped_door_bottom_n.png
git mv -k java/assets/minecraft/textures/block/door_warped_lower_s.png java/assets/minecraft/textures/block/warped_door_bottom_s.png
git mv -k java/assets/minecraft/textures/block/door_warped_lower.png java/assets/minecraft/textures/block/warped_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_warped_upper_n.png java/assets/minecraft/textures/block/warped_door_top_n.png
git mv -k java/assets/minecraft/textures/block/door_warped_upper_s.png java/assets/minecraft/textures/block/warped_door_top_s.png
git mv -k java/assets/minecraft/textures/block/door_warped_upper.png java/assets/minecraft/textures/block/warped_door_top.png
git mv -k java/assets/minecraft/textures/block/door_wood_lower.png java/assets/minecraft/textures/block/oak_door_bottom.png
git mv -k java/assets/minecraft/textures/block/door_wood_upper.png java/assets/minecraft/textures/block/oak_door_top.png
git mv -k java/assets/minecraft/textures/block/end_bricks_n.png java/assets/minecraft/textures/block/end_stone_bricks_n.png
git mv -k java/assets/minecraft/textures/block/end_bricks_s.png java/assets/minecraft/textures/block/end_stone_bricks_s.png
git mv -k java/assets/minecraft/textures/block/end_bricks.png java/assets/minecraft/textures/block/end_stone_bricks.png
git mv -k java/assets/minecraft/textures/block/glass_black_n.png java/assets/minecraft/textures/block/black_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_black_s.png java/assets/minecraft/textures/block/black_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_black.png java/assets/minecraft/textures/block/black_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_blue_n.png java/assets/minecraft/textures/block/blue_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_blue_s.png java/assets/minecraft/textures/block/blue_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_blue.png java/assets/minecraft/textures/block/blue_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_brown_n.png java/assets/minecraft/textures/block/brown_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_brown_s.png java/assets/minecraft/textures/block/brown_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_brown.png java/assets/minecraft/textures/block/brown_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_cyan_n.png java/assets/minecraft/textures/block/cyan_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_cyan_s.png java/assets/minecraft/textures/block/cyan_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_cyan.png java/assets/minecraft/textures/block/cyan_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_gray_n.png java/assets/minecraft/textures/block/gray_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_gray_s.png java/assets/minecraft/textures/block/gray_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_gray.png java/assets/minecraft/textures/block/gray_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_green_n.png java/assets/minecraft/textures/block/green_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_green_s.png java/assets/minecraft/textures/block/green_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_green.png java/assets/minecraft/textures/block/green_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_light_blue_n.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_light_blue_s.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_light_blue.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_lime_n.png java/assets/minecraft/textures/block/lime_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_lime_s.png java/assets/minecraft/textures/block/lime_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_lime.png java/assets/minecraft/textures/block/lime_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_magenta_n.png java/assets/minecraft/textures/block/magenta_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_magenta_s.png java/assets/minecraft/textures/block/magenta_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_magenta.png java/assets/minecraft/textures/block/magenta_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_orange_n.png java/assets/minecraft/textures/block/orange_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_orange_s.png java/assets/minecraft/textures/block/orange_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_orange.png java/assets/minecraft/textures/block/orange_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_black_n.png java/assets/minecraft/textures/block/black_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_black_s.png java/assets/minecraft/textures/block/black_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_black.png java/assets/minecraft/textures/block/black_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_blue_n.png java/assets/minecraft/textures/block/blue_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_blue_s.png java/assets/minecraft/textures/block/blue_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_blue.png java/assets/minecraft/textures/block/blue_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_brown_n.png java/assets/minecraft/textures/block/brown_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_brown_s.png java/assets/minecraft/textures/block/brown_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_brown.png java/assets/minecraft/textures/block/brown_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_cyan_n.png java/assets/minecraft/textures/block/cyan_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_cyan_s.png java/assets/minecraft/textures/block/cyan_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_cyan.png java/assets/minecraft/textures/block/cyan_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_gray_n.png java/assets/minecraft/textures/block/gray_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_gray_s.png java/assets/minecraft/textures/block/gray_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_gray.png java/assets/minecraft/textures/block/gray_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_green_n.png java/assets/minecraft/textures/block/green_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_green_s.png java/assets/minecraft/textures/block/green_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_green.png java/assets/minecraft/textures/block/green_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_light_blue_n.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_light_blue_s.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_light_blue.png java/assets/minecraft/textures/block/light_blue_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_lime_n.png java/assets/minecraft/textures/block/lime_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_lime_s.png java/assets/minecraft/textures/block/lime_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_lime.png java/assets/minecraft/textures/block/lime_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_magenta_n.png java/assets/minecraft/textures/block/magenta_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_magenta_s.png java/assets/minecraft/textures/block/magenta_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_magenta.png java/assets/minecraft/textures/block/magenta_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_orange_n.png java/assets/minecraft/textures/block/orange_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_orange_s.png java/assets/minecraft/textures/block/orange_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_orange.png java/assets/minecraft/textures/block/orange_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_pink_n.png java/assets/minecraft/textures/block/pink_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_pink_s.png java/assets/minecraft/textures/block/pink_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_pink.png java/assets/minecraft/textures/block/pink_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_purple_n.png java/assets/minecraft/textures/block/purple_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_purple_s.png java/assets/minecraft/textures/block/purple_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_purple.png java/assets/minecraft/textures/block/purple_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_red_n.png java/assets/minecraft/textures/block/red_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_red_s.png java/assets/minecraft/textures/block/red_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_red.png java/assets/minecraft/textures/block/red_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_silver_n.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane_top_n.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_silver_s.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane_top_s.png
git mv -k java/assets/minecraft/textures/block/glass_pane_top_silver.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane_top.png
git mv -k java/assets/minecraft/textures/block/glass_pink_n.png java/assets/minecraft/textures/block/pink_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_pink_s.png java/assets/minecraft/textures/block/pink_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_pink.png java/assets/minecraft/textures/block/pink_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_purple_n.png java/assets/minecraft/textures/block/purple_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_purple_s.png java/assets/minecraft/textures/block/purple_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_purple.png java/assets/minecraft/textures/block/purple_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_red_n.png java/assets/minecraft/textures/block/red_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_red_s.png java/assets/minecraft/textures/block/red_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_red.png java/assets/minecraft/textures/block/red_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_silver_n.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_silver_s.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_silver.png java/assets/minecraft/textures/block/light_gray_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_white_n.png java/assets/minecraft/textures/block/white_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_white_s.png java/assets/minecraft/textures/block/white_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_white.png java/assets/minecraft/textures/block/white_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glass_yellow_n.png java/assets/minecraft/textures/block/yellow_stained_glass_pane_n.png
git mv -k java/assets/minecraft/textures/block/glass_yellow_s.png java/assets/minecraft/textures/block/yellow_stained_glass_pane_s.png
git mv -k java/assets/minecraft/textures/block/glass_yellow.png java/assets/minecraft/textures/block/yellow_stained_glass_pane.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_black_n.png java/assets/minecraft/textures/block/black_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_black_s.png java/assets/minecraft/textures/block/black_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_black.png java/assets/minecraft/textures/block/black_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_blue_n.png java/assets/minecraft/textures/block/blue_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_blue_s.png java/assets/minecraft/textures/block/blue_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_blue.png java/assets/minecraft/textures/block/blue_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_brown_n.png java/assets/minecraft/textures/block/brown_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_brown_s.png java/assets/minecraft/textures/block/brown_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_brown.png java/assets/minecraft/textures/block/brown_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_cyan_n.png java/assets/minecraft/textures/block/cyan_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_cyan_s.png java/assets/minecraft/textures/block/cyan_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_cyan.png java/assets/minecraft/textures/block/cyan_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_gray_n.png java/assets/minecraft/textures/block/gray_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_gray_s.png java/assets/minecraft/textures/block/gray_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_gray.png java/assets/minecraft/textures/block/gray_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_green_n.png java/assets/minecraft/textures/block/green_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_green_s.png java/assets/minecraft/textures/block/green_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_green.png java/assets/minecraft/textures/block/green_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_light_blue_n.png java/assets/minecraft/textures/block/light_blue_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_light_blue_s.png java/assets/minecraft/textures/block/light_blue_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_light_blue.png java/assets/minecraft/textures/block/light_blue_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_lime_n.png java/assets/minecraft/textures/block/lime_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_lime_s.png java/assets/minecraft/textures/block/lime_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_lime.png java/assets/minecraft/textures/block/lime_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_magenta_n.png java/assets/minecraft/textures/block/magenta_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_magenta_s.png java/assets/minecraft/textures/block/magenta_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_magenta.png java/assets/minecraft/textures/block/magenta_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_orange_n.png java/assets/minecraft/textures/block/orange_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_orange_s.png java/assets/minecraft/textures/block/orange_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_orange.png java/assets/minecraft/textures/block/orange_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_pink_n.png java/assets/minecraft/textures/block/pink_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_pink_s.png java/assets/minecraft/textures/block/pink_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_pink.png java/assets/minecraft/textures/block/pink_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_purple_n.png java/assets/minecraft/textures/block/purple_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_purple_s.png java/assets/minecraft/textures/block/purple_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_purple.png java/assets/minecraft/textures/block/purple_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_red_n.png java/assets/minecraft/textures/block/red_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_red_s.png java/assets/minecraft/textures/block/red_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_red.png java/assets/minecraft/textures/block/red_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_silver_n.png java/assets/minecraft/textures/block/light_gray_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_silver_s.png java/assets/minecraft/textures/block/light_gray_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_silver.png java/assets/minecraft/textures/block/light_gray_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_white_n.png java/assets/minecraft/textures/block/white_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_white_s.png java/assets/minecraft/textures/block/white_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_white.png java/assets/minecraft/textures/block/white_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_yellow_n.png java/assets/minecraft/textures/block/yellow_glazed_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_yellow_s.png java/assets/minecraft/textures/block/yellow_glazed_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/glazed_terracotta_yellow.png java/assets/minecraft/textures/block/yellow_glazed_terracotta.png
git mv -k java/assets/minecraft/textures/block/grass_path_side_n.png java/assets/minecraft/textures/block/dirt_path_side_n.png
git mv -k java/assets/minecraft/textures/block/grass_path_side_s.png java/assets/minecraft/textures/block/dirt_path_side_s.png
git mv -k java/assets/minecraft/textures/block/grass_path_side.png java/assets/minecraft/textures/block/dirt_path_side.png
git mv -k java/assets/minecraft/textures/block/grass_path_top_n.png java/assets/minecraft/textures/block/dirt_path_n.png
git mv -k java/assets/minecraft/textures/block/grass_path_top_s.png java/assets/minecraft/textures/block/dirt_path_s.png
git mv -k java/assets/minecraft/textures/block/grass_path_top.png java/assets/minecraft/textures/block/dirt_path.png
git mv -k java/assets/minecraft/textures/block/grass_side_n.png java/assets/minecraft/textures/block/grass_block_side_n.png
git mv -k java/assets/minecraft/textures/block/grass_side_s.png java/assets/minecraft/textures/block/grass_block_side_s.png
git mv -k java/assets/minecraft/textures/block/grass_side.tga java/assets/minecraft/textures/block/grass_block_side.tga
git mv -k java/assets/minecraft/textures/block/grass_top_n.png java/assets/minecraft/textures/block/grass_block_top_n.png
git mv -k java/assets/minecraft/textures/block/grass_top_s.png java/assets/minecraft/textures/block/grass_block_top_s.png
git mv -k java/assets/minecraft/textures/block/grass_top.png java/assets/minecraft/textures/block/grass_block_top.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_black_n.png java/assets/minecraft/textures/block/black_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_black_s.png java/assets/minecraft/textures/block/black_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_black.png java/assets/minecraft/textures/block/black_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_blue_n.png java/assets/minecraft/textures/block/blue_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_blue_s.png java/assets/minecraft/textures/block/blue_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_blue.png java/assets/minecraft/textures/block/blue_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_brown_n.png java/assets/minecraft/textures/block/brown_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_brown_s.png java/assets/minecraft/textures/block/brown_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_brown.png java/assets/minecraft/textures/block/brown_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_cyan_n.png java/assets/minecraft/textures/block/cyan_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_cyan_s.png java/assets/minecraft/textures/block/cyan_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_cyan.png java/assets/minecraft/textures/block/cyan_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_gray_n.png java/assets/minecraft/textures/block/gray_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_gray_s.png java/assets/minecraft/textures/block/gray_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_gray.png java/assets/minecraft/textures/block/gray_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_green_n.png java/assets/minecraft/textures/block/green_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_green_s.png java/assets/minecraft/textures/block/green_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_green.png java/assets/minecraft/textures/block/green_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_light_blue_n.png java/assets/minecraft/textures/block/light_blue_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_light_blue_s.png java/assets/minecraft/textures/block/light_blue_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_light_blue.png java/assets/minecraft/textures/block/light_blue_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_lime_n.png java/assets/minecraft/textures/block/lime_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_lime_s.png java/assets/minecraft/textures/block/lime_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_lime.png java/assets/minecraft/textures/block/lime_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_magenta_n.png java/assets/minecraft/textures/block/magenta_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_magenta_s.png java/assets/minecraft/textures/block/magenta_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_magenta.png java/assets/minecraft/textures/block/magenta_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_orange_n.png java/assets/minecraft/textures/block/orange_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_orange_s.png java/assets/minecraft/textures/block/orange_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_orange.png java/assets/minecraft/textures/block/orange_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_pink_n.png java/assets/minecraft/textures/block/pink_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_pink_s.png java/assets/minecraft/textures/block/pink_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_pink.png java/assets/minecraft/textures/block/pink_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_purple_n.png java/assets/minecraft/textures/block/purple_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_purple_s.png java/assets/minecraft/textures/block/purple_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_purple.png java/assets/minecraft/textures/block/purple_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_red_n.png java/assets/minecraft/textures/block/red_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_red_s.png java/assets/minecraft/textures/block/red_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_red.png java/assets/minecraft/textures/block/red_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_silver_n.png java/assets/minecraft/textures/block/light_gray_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_silver_s.png java/assets/minecraft/textures/block/light_gray_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_silver.png java/assets/minecraft/textures/block/light_gray_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_white_n.png java/assets/minecraft/textures/block/white_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_white_s.png java/assets/minecraft/textures/block/white_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_white.png java/assets/minecraft/textures/block/white_terracotta.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_yellow_n.png java/assets/minecraft/textures/block/yellow_terracotta_n.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_yellow_s.png java/assets/minecraft/textures/block/yellow_terracotta_s.png
git mv -k java/assets/minecraft/textures/block/hardened_clay_stained_yellow.png java/assets/minecraft/textures/block/yellow_terracotta.png
git mv -k java/assets/minecraft/textures/block/log_acacia_n.png java/assets/minecraft/textures/block/acacia_log_n.png
git mv -k java/assets/minecraft/textures/block/log_acacia_s.png java/assets/minecraft/textures/block/acacia_log_s.png
git mv -k java/assets/minecraft/textures/block/log_acacia_top_n.png java/assets/minecraft/textures/block/acacia_log_top_n.png
git mv -k java/assets/minecraft/textures/block/log_acacia_top_s.png java/assets/minecraft/textures/block/acacia_log_top_s.png
git mv -k java/assets/minecraft/textures/block/log_acacia_top.png java/assets/minecraft/textures/block/acacia_log_top.png
git mv -k java/assets/minecraft/textures/block/log_acacia.png java/assets/minecraft/textures/block/acacia_log.png
git mv -k java/assets/minecraft/textures/block/log_birch_n.png java/assets/minecraft/textures/block/birch_log_n.png
git mv -k java/assets/minecraft/textures/block/log_birch_s.png java/assets/minecraft/textures/block/birch_log_s.png
git mv -k java/assets/minecraft/textures/block/log_birch_top_n.png java/assets/minecraft/textures/block/birch_log_top_n.png
git mv -k java/assets/minecraft/textures/block/log_birch_top_s.png java/assets/minecraft/textures/block/birch_log_top_s.png
git mv -k java/assets/minecraft/textures/block/log_birch_top.png java/assets/minecraft/textures/block/birch_log_top.png
git mv -k java/assets/minecraft/textures/block/log_birch.png java/assets/minecraft/textures/block/birch_log.png
git mv -k java/assets/minecraft/textures/block/log_oak_n.png java/assets/minecraft/textures/block/oak_log_n.png
git mv -k java/assets/minecraft/textures/block/log_oak_s.png java/assets/minecraft/textures/block/oak_log_s.png
git mv -k java/assets/minecraft/textures/block/log_oak_top_n.png java/assets/minecraft/textures/block/oak_log_top_n.png
git mv -k java/assets/minecraft/textures/block/log_oak_top_s.png java/assets/minecraft/textures/block/oak_log_top_s.png
git mv -k java/assets/minecraft/textures/block/log_oak_top.png java/assets/minecraft/textures/block/oak_log_top.png
git mv -k java/assets/minecraft/textures/block/log_oak.png java/assets/minecraft/textures/block/oak_log.png
git mv -k java/assets/minecraft/textures/block/log_spruce_n.png java/assets/minecraft/textures/block/spruce_log_n.png
git mv -k java/assets/minecraft/textures/block/log_spruce_s.png java/assets/minecraft/textures/block/spruce_log_s.png
git mv -k java/assets/minecraft/textures/block/log_spruce_top_n.png java/assets/minecraft/textures/block/spruce_log_top_n.png
git mv -k java/assets/minecraft/textures/block/log_spruce_top_s.png java/assets/minecraft/textures/block/spruce_log_top_s.png
git mv -k java/assets/minecraft/textures/block/log_spruce_top.png java/assets/minecraft/textures/block/spruce_log_top.png
git mv -k java/assets/minecraft/textures/block/log_spruce.png java/assets/minecraft/textures/block/spruce_log.png
git mv -k java/assets/minecraft/textures/block/planks_acacia_n.png java/assets/minecraft/textures/block/acacia_planks_n.png
git mv -k java/assets/minecraft/textures/block/planks_acacia_s.png java/assets/minecraft/textures/block/acacia_planks_s.png
git mv -k java/assets/minecraft/textures/block/planks_acacia.png java/assets/minecraft/textures/block/acacia_planks.png
git mv -k java/assets/minecraft/textures/block/planks_birch_n.png java/assets/minecraft/textures/block/birch_planks_n.png
git mv -k java/assets/minecraft/textures/block/planks_birch_s.png java/assets/minecraft/textures/block/birch_planks_s.png
git mv -k java/assets/minecraft/textures/block/planks_birch.png java/assets/minecraft/textures/block/birch_planks.png
git mv -k java/assets/minecraft/textures/block/planks_dark_oak_n.png java/assets/minecraft/textures/block/dark_oak_planks_n.png
git mv -k java/assets/minecraft/textures/block/planks_dark_oak_s.png java/assets/minecraft/textures/block/dark_oak_planks_s.png
git mv -k java/assets/minecraft/textures/block/planks_dark_oak.png java/assets/minecraft/textures/block/dark_oak_planks.png
git mv -k java/assets/minecraft/textures/block/planks_jungle_n.png java/assets/minecraft/textures/block/jungle_planks_n.png
git mv -k java/assets/minecraft/textures/block/planks_jungle_s.png java/assets/minecraft/textures/block/jungle_planks_s.png
git mv -k java/assets/minecraft/textures/block/planks_jungle.png java/assets/minecraft/textures/block/jungle_planks.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled_n.png java/assets/minecraft/textures/block/chiseled_quartz_block_n.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled_s.png java/assets/minecraft/textures/block/chiseled_quartz_block_s.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled_top_n.png java/assets/minecraft/textures/block/chiseled_quartz_block_top_n.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled_top_s.png java/assets/minecraft/textures/block/chiseled_quartz_block_top_s.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled_top.png java/assets/minecraft/textures/block/chiseled_quartz_block_top.png
git mv -k java/assets/minecraft/textures/block/quartz_block_chiseled.png java/assets/minecraft/textures/block/chiseled_quartz_block.png
git mv -k java/assets/minecraft/textures/block/quartz_block_lines_n.png java/assets/minecraft/textures/block/quartz_pillar_n.png
git mv -k java/assets/minecraft/textures/block/quartz_block_lines_s.png java/assets/minecraft/textures/block/quartz_pillar_s.png
git mv -k java/assets/minecraft/textures/block/quartz_block_lines.png java/assets/minecraft/textures/block/quartz_pillar.png
git mv -k java/assets/minecraft/textures/block/stone_andesite_n.png java/assets/minecraft/textures/block/andesite_n.png
git mv -k java/assets/minecraft/textures/block/stone_andesite_s.png java/assets/minecraft/textures/block/andesite_s.png
git mv -k java/assets/minecraft/textures/block/stone_andesite.png java/assets/minecraft/textures/block/andesite.png
git mv -k java/assets/minecraft/textures/block/stone_diorite_n.png java/assets/minecraft/textures/block/diorite_n.png
git mv -k java/assets/minecraft/textures/block/stone_diorite_s.png java/assets/minecraft/textures/block/diorite_s.png
git mv -k java/assets/minecraft/textures/block/stone_diorite.png java/assets/minecraft/textures/block/diorite.png
git mv -k java/assets/minecraft/textures/block/stone_granite_n.png java/assets/minecraft/textures/block/granite_n.png
git mv -k java/assets/minecraft/textures/block/stone_granite_s.png java/assets/minecraft/textures/block/granite_s.png
git mv -k java/assets/minecraft/textures/block/stone_granite.png java/assets/minecraft/textures/block/granite.png
git mv -k java/assets/minecraft/textures/block/stonebrick_carved_n.png java/assets/minecraft/textures/block/chiseled_stone_bricks_n.png
git mv -k java/assets/minecraft/textures/block/stonebrick_carved_s.png java/assets/minecraft/textures/block/chiseled_stone_bricks_s.png
git mv -k java/assets/minecraft/textures/block/stonebrick_carved.png java/assets/minecraft/textures/block/chiseled_stone_bricks.png
git mv -k java/assets/minecraft/textures/block/stonebrick_cracked_n.png java/assets/minecraft/textures/block/cracked_stone_bricks_n.png
git mv -k java/assets/minecraft/textures/block/stonebrick_cracked_s.png java/assets/minecraft/textures/block/cracked_stone_bricks_s.png
git mv -k java/assets/minecraft/textures/block/stonebrick_cracked.png java/assets/minecraft/textures/block/cracked_stone_bricks.png
git mv -k java/assets/minecraft/textures/block/stonebrick_mossy_n.png java/assets/minecraft/textures/block/mossy_stone_bricks_n.png
git mv -k java/assets/minecraft/textures/block/stonebrick_mossy_s.png java/assets/minecraft/textures/block/mossy_stone_bricks_s.png
git mv -k java/assets/minecraft/textures/block/stonebrick_mossy.png java/assets/minecraft/textures/block/mossy_stone_bricks.png
git mv -k java/assets/minecraft/textures/block/stonebrick_n.png java/assets/minecraft/textures/block/stone_bricks_n.png
git mv -k java/assets/minecraft/textures/block/stonebrick_s.png java/assets/minecraft/textures/block/stone_bricks_s.png
git mv -k java/assets/minecraft/textures/block/stonebrick.png java/assets/minecraft/textures/block/stone_bricks.png
git mv -k java/assets/minecraft/textures/block/wool_colored_black_n.png java/assets/minecraft/textures/block/black_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_black_s.png java/assets/minecraft/textures/block/black_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_black.png java/assets/minecraft/textures/block/black_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_blue_n.png java/assets/minecraft/textures/block/blue_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_blue_s.png java/assets/minecraft/textures/block/blue_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_blue.png java/assets/minecraft/textures/block/blue_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_brown_n.png java/assets/minecraft/textures/block/brown_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_brown_s.png java/assets/minecraft/textures/block/brown_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_brown.png java/assets/minecraft/textures/block/brown_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_cyan_n.png java/assets/minecraft/textures/block/cyan_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_cyan_s.png java/assets/minecraft/textures/block/cyan_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_cyan.png java/assets/minecraft/textures/block/cyan_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_gray_n.png java/assets/minecraft/textures/block/gray_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_gray_s.png java/assets/minecraft/textures/block/gray_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_gray.png java/assets/minecraft/textures/block/gray_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_green_n.png java/assets/minecraft/textures/block/green_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_green_s.png java/assets/minecraft/textures/block/green_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_green.png java/assets/minecraft/textures/block/green_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_light_blue_n.png java/assets/minecraft/textures/block/light_blue_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_light_blue_s.png java/assets/minecraft/textures/block/light_blue_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_light_blue.png java/assets/minecraft/textures/block/light_blue_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_lime_n.png java/assets/minecraft/textures/block/lime_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_lime_s.png java/assets/minecraft/textures/block/lime_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_lime.png java/assets/minecraft/textures/block/lime_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_magenta_n.png java/assets/minecraft/textures/block/magenta_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_magenta.png java/assets/minecraft/textures/block/magenta_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_orange_s.png java/assets/minecraft/textures/block/orange_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_orange.png java/assets/minecraft/textures/block/orange_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_organge_n.png java/assets/minecraft/textures/block/organge_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_pink_n.png java/assets/minecraft/textures/block/pink_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_pink_s.png java/assets/minecraft/textures/block/pink_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_pink.png java/assets/minecraft/textures/block/pink_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_purple_n.png java/assets/minecraft/textures/block/purple_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_purple_s.png java/assets/minecraft/textures/block/purple_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_purple.png java/assets/minecraft/textures/block/purple_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_red_n.png java/assets/minecraft/textures/block/red_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_red_s.png java/assets/minecraft/textures/block/red_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_red.png java/assets/minecraft/textures/block/red_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_silver_n.png java/assets/minecraft/textures/block/light_gray_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_silver_s.png java/assets/minecraft/textures/block/light_gray_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_silver.png java/assets/minecraft/textures/block/light_gray_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_white_n.png java/assets/minecraft/textures/block/white_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_white_s.png java/assets/minecraft/textures/block/white_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_white.png java/assets/minecraft/textures/block/white_wool.png
git mv -k java/assets/minecraft/textures/block/wool_colored_yellow_n.png java/assets/minecraft/textures/block/yellow_wool_n.png
git mv -k java/assets/minecraft/textures/block/wool_colored_yellow_s.png java/assets/minecraft/textures/block/yellow_wool_s.png
git mv -k java/assets/minecraft/textures/block/wool_colored_yellow.png java/assets/minecraft/textures/block/yellow_wool.png
git mv -k java/assets/minecraft/textures/block/redstone_lamp_off_n.png java/assets/minecraft/textures/block/redstone_lamp_n.png
git mv -k java/assets/minecraft/textures/block/redstone_lamp_off_s.png java/assets/minecraft/textures/block/redstone_lamp_s.png
git mv -k java/assets/minecraft/textures/block/redstone_lamp_off.png java/assets/minecraft/textures/block/redstone_lamp.png
git mv -k java/assets/minecraft/textures/block/redstone_torch_on_n.png java/assets/minecraft/textures/block/redstone_torch_n.png
git mv -k java/assets/minecraft/textures/block/redstone_torch_on_s.png java/assets/minecraft/textures/block/redstone_torch_s.png
git mv -k java/assets/minecraft/textures/block/redstone_torch_on.png java/assets/minecraft/textures/block/redstone_torch.png
git mv -k java/assets/minecraft/textures/block/reeds_n.png java/assets/minecraft/textures/block/sugar_cane_n.png
git mv -k java/assets/minecraft/textures/block/reeds_s.png java/assets/minecraft/textures/block/sugar_cane_s.png
git mv -k java/assets/minecraft/textures/block/reeds.png java/assets/minecraft/textures/block/sugar_cane.png
git mv -k java/assets/minecraft/textures/block/stone_andesite_smooth_n.png java/assets/minecraft/textures/block/polished_andesite_n.png
git mv -k java/assets/minecraft/textures/block/stone_andesite_smooth_s.png java/assets/minecraft/textures/block/polished_andesite_s.png
git mv -k java/assets/minecraft/textures/block/stone_andesite_smooth.png java/assets/minecraft/textures/block/polished_andesite.png
git mv -k java/assets/minecraft/textures/block/stone_diorite_smooth_n.png java/assets/minecraft/textures/block/polished_diorite_n.png
git mv -k java/assets/minecraft/textures/block/stone_diorite_smooth_s.png java/assets/minecraft/textures/block/polished_diorite_s.png
git mv -k java/assets/minecraft/textures/block/stone_diorite_smooth.png java/assets/minecraft/textures/block/polished_diorite.png
git mv -k java/assets/minecraft/textures/block/stone_granite_smooth_n.png java/assets/minecraft/textures/block/polished_granite_n.png
git mv -k java/assets/minecraft/textures/block/stone_granite_smooth_s.png java/assets/minecraft/textures/block/polished_granite_s.png
git mv -k java/assets/minecraft/textures/block/stone_granite_smooth.png java/assets/minecraft/textures/block/polished_granite.png
git mv -k java/assets/minecraft/textures/block/prismarine_dark_n.png java/assets/minecraft/textures/block/dark_prismarine_n.png
git mv -k java/assets/minecraft/textures/block/prismarine_dark_s.png java/assets/minecraft/textures/block/dark_prismarine_s.png
git mv -k java/assets/minecraft/textures/block/prismarine_dark.png java/assets/minecraft/textures/block/dark_prismarine.png
git mv -k java/assets/minecraft/textures/block/rail_detector_n.png java/assets/minecraft/textures/block/detector_rail_n.png
git mv -k java/assets/minecraft/textures/block/rail_detector_s.png java/assets/minecraft/textures/block/detector_rail_s.png
git mv -k java/assets/minecraft/textures/block/rail_detector.png java/assets/minecraft/textures/block/detector_rail.png
git mv -k java/assets/minecraft/textures/block/rail_activator_n.png java/assets/minecraft/textures/block/activator_rail_n.png
git mv -k java/assets/minecraft/textures/block/rail_activator_s.png java/assets/minecraft/textures/block/activator_rail_s.png
git mv -k java/assets/minecraft/textures/block/rail_activator.png java/assets/minecraft/textures/block/activator_rail.png