name: PBR JG
description: Java conversion of JG RTX resource pack
author: Jason J. Gardner
input:
  format: raw
profiles:
- edition: Java
  format: 9
  name: PBR JG
  description: Java conversion of JG RTX resource pack
  tags: pbr, labpbr
  encoding:
    image: png
    format: lab-1.3
    sampler: bilinear
  texture-size: 256
  block-texture-size: 256
  item-texture-size: 128
  texture-scale: 1
  auto-level-height: true
  auto-generate-normal: false
