name: Bedrock Branch

on:
    push:
        branches: [ main ]
        

permissions: write-all

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v3
              with:
                  ref: main
                  fetch-depth: 0
            - name: Sync main to bedrock
              run: |
                  git checkout bedrock
                  rsync -av bedrock/pack .
                  git add ./RP
                  git merge main
                  git push origin bedrock
