name: Create .mcpack from RP directory in repository

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    name: Create .mcpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource pack contents
        uses: actions/checkout@v2
        
      - name: Build mcpack archive
        run: |
          sudo apt-get update
          sudo apt-get -y install zip
          cd ${GITHUB_WORKSPACE}
          zip -r -0 JG-RTX.mcpack ./RP
