name: .mcpack

on:
  push:
    branches:
      - main
    paths:
      - 'RP/**'
      
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: JG-RTX
          path: |
            RP/**/*
