name: Mineways
on:
  workflow_dispatch:

jobs:
  mineways:
    runs-on: windows-latest
    steps:
      - name: Download Mineways
        id: download-mineways
        run: |
          mkdir $env:GITHUB_WORKSPACE\bin
          Invoke-WebRequest -URI https://erich.realtimerendering.com/minecraft/public/mineways/mineways.zip -OutFile bin\mineways.zip
      - name: Extract Mineways
        id: extract-mineways
        run: |
          cd $env:GITHUB_WORKSPACE\bin
          7z x .\mineways.zip
      - name: Create terrain texture
        id: run-mineways
        run: |
          mkdir $env:GITHUB_WORKSPACE\dist
          cd $env:GITHUB_WORKSPACE\bin\mineways\TileMaker
          ChannelMixer.exe -i $env:GITHUB_WORKSPACE\bedrock\pack\RP -o $env:GITHUB_WORKSPACE\dist\mineways\blocks
          TileMaker.exe -d $env:GITHUB_WORKSPACE\dist\mineways\blocks -o $env:GITHUB_WORKSPACE\dist\mineways\terrainExtJG-RTX.png
      - name: Upload terrain texture
        uses: actions/upload-artifact@v2
        with:
          name: terrainExtJG-RTX.png
          path: dist/mineways/terrainExtJG-RTX.png
