name: Mineways
on:
  workflow_dispatch:

jobs:
  mineways:
    env:
      PACK_PATH: ${{ github.workspace }}\bedrock\pack\RP
      TILE_PATH: ${{ github.workspace }}\dist\mineways\blocks
      MINEWAYS_URL: https://erich.realtimerendering.com/minecraft/public/mineways/mineways.zip
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-mineways
        with:
          path: |
            bin\mineways\TileMaker\ChannelMixer.exe
            bin\mineways\TileMaker\TileMaker.exe
            bin\mineways\TileMaker\textures\water_normal.png
            bin\mineways\TileMaker\terrainBase.png
          key: mineways-tilemaker
          restore-keys: |
            mineways-tilemaker
      - name: Download and unzip Mineways
        id: download-mineways
        if: steps.cache-mineways.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          mkdir ${{ github.workspace }}\bin
          cd ${{ github.workspace }}\bin
          Invoke-WebRequest -URI ${env:MINEWAYS_URL} -OutFile mineways.zip
          7z x .\mineways.zip
          echo "### Extracted Mineways" >> $GITHUB_STEP_SUMMARY
      - name: Create terrain texture
        id: run-mineways
        run: |
          mkdir ${env:TILE_PATH}
          cd ${{ github.workspace }}\bin\mineways\TileMaker
          .\ChannelMixer.exe -i ${env:PACK_PATH} -o ${env:TILE_PATH}
          .\TileMaker.exe -d ${env:TILE_PATH} -o ${{ github.workspace }}\dist\mineways\terrainExtJG-RTX.png
      - name: Upload terrain texture
        uses: actions/upload-artifact@v2
        with:
          name: terrainExtJG-RTX.png
          path: dist/mineways/terrainExtJG-RTX.png
