name: Mineways
on:
  workflow_dispatch:

jobs:
  mineways:
    env:
      MINEWAYS_URL: https://erich.realtimerendering.com/minecraft/public/mineways/mineways.zip
      # Path to input resource pack
      PACK_PATH: ${{ github.workspace }}\bedrock\pack\RP
      # Path to ChannelMixer output / TileMaker input
      TILE_PATH: ${{ github.workspace }}\dist\mineways\blocks
      # Path to TileMaker executables
      TM_PATH: ${{ github.workspace }}\bin\mineways\TileMaker
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-mineways
        with:
          path: |
            ${{ env.TM_PATH }}/ChannelMixer.exe
            ${{ env.TM_PATH }}/TileMaker.exe
            ${{ env.TM_PATH }}/textures/water_normal.png
            ${{ env.TM_PATH }}/terrainBase.png
          key: mineways-tilemaker
          restore-keys: |
            mineways-tilemaker
      - name: Download and unzip Mineways
        id: download-mineways
        if: steps.cache-mineways.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          mkdir ${{ github.workspace }}\bin
          cd ${{ github.workspace }}\bin
          Invoke-WebRequest -URI ${env:MINEWAYS_URL} -OutFile mineways.zip
          7z x .\mineways.zip
          echo "### Extracted Mineways" >> $env:GITHUB_STEP_SUMMARY
          echo "${env:GITHUB_WORKSPACE}\bin\mineways\TileMaker" >> $env:GITHUB_PATH
      - name: Create terrain texture
        id: run-mineways
        run: |
          mkdir $env:TILE_PATH
          cd $env:TM_PATH
          .\ChannelMixer.exe -i $env:PACK_PATH -o $env:TILE_PATH
          .\TileMaker.exe -d $env:TILE_PATH -o ${env:GITHUB_WORKSPACE}\dist\mineways\terrainExtJG-RTX.png
      - name: Upload terrain texture
        uses: actions/upload-artifact@v2
        with:
          name: terrainExtJG-RTX
          path: dist/mineways/*.png
