name: Mineways
on:
  workflow_dispatch:

jobs:
  mineways:
    runs-on: windows-latest
    steps:
      - name: Download Mineways
        id: download-mineways
        run: |
          mkdir ${{ github.workspace }}\bin
          cd ${{ github.workspace }}\bin
          Invoke-WebRequest -URI https://erich.realtimerendering.com/minecraft/public/mineways/mineways.zip -OutFile mineways.zip
          7z x .\mineways.zip
      - name: Create terrain texture
        id: run-mineways
        run: |
          mkdir ${{ github.workspace }}\dist
          ${{ github.workspace }}\bin\mineways\TileMaker\ChannelMixer.exe -i ${{ github.workspace }}\bin\mineways\TileMaker\bedrock\pack\RP -o ${{ github.workspace }}\bin\mineways\TileMaker\dist\mineways\blocks
          ${{ github.workspace }}\bin\mineways\TileMaker\TileMaker.exe -d ${{ github.workspace }}\bin\mineways\TileMaker\dist\mineways\blocks -o ${{ github.workspace }}\bin\mineways\TileMaker\dist\mineways\terrainExtJG-RTX.png
      - name: Upload terrain texture
        uses: actions/upload-artifact@v2
        with:
          name: terrainExtJG-RTX.png
          path: dist/mineways/terrainExtJG-RTX.png
