name: Preview Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bedrock/**'
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      run: |
        mkdir dist
    - name: Copy main pack
      run: |
        cp -r bedrock/pack dist
        (cd bedrock/pack; zip -0 -r ../JG-RTX.mcpack .)
    - name: Copy addon pack
      run: |
        cp -r bedrock/addon/ dist
        (cd dist/addon; zip -0 -r ../JG-RTX.mcaddon .)
    - name: Copy variety packs
      run: |
        cp -r bedrock/variety/glass/ dist/glass_variety
        (cd dist/glass_variety; zip -0 -r ../JG-RTX_glass.mcpack .)
        cp -r bedrock/variety/modern/ dist/modern_variety
        (cd dist/modern_variety; zip -0 -r ../JG-RTX_modern.mcpack .)
        cp -r bedrock/variety/vanilla/ dist/vanilla_variety
        (cd dist/vanilla_variety; zip -0 -r ../JG-RTX_vanilla.mcpack .)
    - name: Upload Bedrock packs
      uses: actions/upload-artifact@v2
      with:
        name: JG-RTX
        path: /*.mc*
