name: Nightly Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bedrock/**'
      - 'java/**'

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Zip Java directory
        run: |
          mkdir dist
          cp -r java dist
          cd dist/java
          zip -0 -r ../PBR-JG.zip .
      - name: Upload pack archive
        uses: actions/upload-artifact@v2
        with:
          name: PBR-JG
          path: dist/PBR-JG.zip
  bedrock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ZIP Bedrock directories
        run: |
          mkdir dist
          cp -r bedrock/pack dist
          cp -r bedrock/addon dist
          cp -r bedrock/variety dist
          cd dist/pack
          zip -0 -r ../JG-RTX.mcpack .
          cd ../addon
          zip -0 -r ../JG-RTX.mcaddon .
          cd ../variety
          zip -0 -r ../JG-RTX_GlassVariety.mcpack ./glass
      - name: Upload mcpack
        uses: actions/upload-artifact@v2
        with:
          name: JG-RTX
          path: dist/*.mc*
