name: Preview Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bedrock/**'
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Zip directories
      run: |
        mkdir dist
        cp -r bedrock/pack dist
        cp -r bedrock/addon dist
        cp -r bedrock/variety dist
        cd ../pack
        zip -0 -r ../JG-RTX.mcpack .
        cd ../addon
        zip -0 -r ../JG-RTX.mcaddon .
        cd ../variety
        zip -0 -r ../JG-RTX_GlassVariety.mcpack ./glass
    - name: Upload Bedrock packs
      uses: actions/upload-artifact@v2
      with:
        name: JG-RTX
        path: dist/*.mc*
