name: Build Bedrock packs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bedrock/**'
jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Run workflow script
        run: deno run --allow-read --allow-write --allow-net --allow-env .github/workflows/scripts/createPack.ts

      - name: Upload Bedrock packs
        uses: actions/upload-artifact@v2
        with:
          name: JG-RTX
          path: ./*.mc*
