
name: PixelGraph
on:
  workflow_dispatch:

jobs:
  labPbr_256x:
    name: LabPbr-256x
    runs-on: ubuntu-latest
    needs: []
    env:
      release_filename: PBR-JG-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr-256x
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/pixelgraph/project.yml
          profile: PBR-JG-256x
          zip: PBR-JG.zip
      - name: Release LabPbr-32x
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./dist/PBR-JG.zip
          asset_name: PBR JG
          asset_content_type: application/zip
