name: Create release

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:

jobs:
  build:
    name: Release .mcpack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resource pack contents
        uses: actions/checkout@v2
        
      - name: Create mcpack with release
        uses: ncipollo/release-action@v1.8.6
        with:
          commit: main
          artifacts: ${{ github.workspace }}/RP
          artifactErrorsFailBuild: true,
          artifactContentType: application/zip
          #bodyFile: CHANGELOG.md
          draft: true,
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
