name: mcpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create mcpack artifact
        uses: actions/upload-artifact@v2
        with:
          name: JG-RTX.mcpack
          path: ${{ github.workspace }}/RP
